version: '3.9'
services:
  postgres:
    container_name: event-booking-db
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      PGDATA: /var/lib/postgresql/data
      POSTGRES_DB: event_booking
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - spring-demo

  ### Postgres Adminer ###
  postgres_admin:
    image: dpage/pgadmin4
    restart: always
    depends_on:
      - postgres
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.ng
      PGADMIN_DEFAULT_PASSWORD: password
    ports:
      - "5051:80"

  booking-app-api:
    container_name: booking-app-api
    image: booking-app/booking-app:1.0.0
    ports:
      - "8088:8088"
    networks:
      - spring-demo
    depends_on:
      - postgres


networks:
  spring-demo:
    driver: bridge

volumes:
  postgres:
    driver: local